#!/usr/bin/env node
// Renders spec/wire-traces.mdx from examples/v0.1/traces/*.jsonl. `--check` fails on drift. Apache-2.0.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT, emit } from "./lib.mjs";

const check = process.argv.includes("--check");
const DIR = join(ROOT, "examples", "v0.1", "traces");

const TRACES = [
  { file: "core-lockstep.jsonl", title: "Core flow, lockstep",
    intro: "Discovery, session opening, the initial observation, one extended action across two advances with progress and completion, and closure, on the inline binding against a grid world." },
  { file: "core-streaming.jsonl", title: "Core flow, streaming",
    intro: "The same flow against a streaming manipulator: clock synchronization on the heartbeat, frames with capture and send time, a submission naming its basis, progress, completion, telemetry in both directions, and closure." },
  { file: "cancel.jsonl", title: "Cancellation during execution",
    intro: "An executing extended action is cancelled: the world enters cancelling, completes its safe abort, and reports cancelled with the progress reached." },
  { file: "disconnect.jsonl", title: "Disconnection, watchdog, resumption",
    intro: "The control connection drops mid-execution. The watchdog enters safe state and terminates the action while the agent is away; the agent reconnects, resumes, receives every missed notification in order, and regains control with a new submission." },
];

const esc = (s) => s.replace(/</g, "&lt;").replace(/\{/g, "&#123;").replace(/\}/g, "&#125;");
const arrow = (from) => (from === "agent" ? "agent → world" : "world → agent");

// JSON with two-space indent, arrays of primitives kept on one line.
function pretty(v, indent = "") {
  if (Array.isArray(v)) {
    if (v.every((x) => x === null || typeof x !== "object")) return JSON.stringify(v).replace(/,/g, ", ");
    return "[\n" + v.map((x) => indent + "  " + pretty(x, indent + "  ")).join(",\n") + "\n" + indent + "]";
  }
  if (v && typeof v === "object") {
    const entries = Object.entries(v);
    if (!entries.length) return "{}";
    return "{\n" + entries.map(([k, x]) => `${indent}  ${JSON.stringify(k)}: ${pretty(x, indent + "  ")}`).join(",\n") + "\n" + indent + "}";
  }
  return JSON.stringify(v);
}

let out = `---
title: "Wire traces"
description: "Complete, validated message sequences: discovery and session opening, the lockstep and streaming loops, cancellation, and disconnection with recovery."
---

{/* GENERATED by scripts/gen-traces.mjs from examples/v0.1/traces/*.jsonl — do not edit by hand. */}

<Note>
Each trace is a JSON Lines file under [\`examples/v0.1/traces/\`](https://github.com/Hyperduality/agent-world-protocol/tree/main/examples/v0.1/traces). Every line is either a message, \`{ from, step, msg }\`, or a transport event that is not a message, \`{ marker }\`. CI validates every message against the canonical schema for its method, matches every response to its request, checks that \`status_seq\` increases by exactly one across statuses, events, and session-state notifications (AWP-CTL-008), and checks frame \`seq\` per channel (AWP-DAT-001). Tokens are illustrative.
</Note>

`;
let allOk = true;
for (const t of TRACES) {
  const lines = readFileSync(join(DIR, t.file), "utf8").split("\n").filter((l) => l.trim());
  out += `## ${t.title}\n\n${t.intro} Source: [\`${t.file}\`](https://github.com/Hyperduality/agent-world-protocol/blob/main/examples/v0.1/traces/${t.file}).\n\n`;
  let n = 0;
  for (const line of lines) {
    const e = JSON.parse(line);
    if (e.marker) { out += `> **Transport.** ${esc(e.marker)}\n\n`; continue; }
    n++;
    out += `**${n}. ${esc(e.step)}** — ${arrow(e.from)}\n\n\`\`\`json\n${pretty(e.msg)}\n\`\`\`\n\n`;
  }
}
allOk = emit(join(ROOT, "spec", "wire-traces.mdx"), out, check);
process.exit(allOk ? 0 : 1);
