#!/usr/bin/env node
// Renders spec/wire-traces.mdx from examples/v0.1/traces/*.jsonl. `--check` fails on drift. Apache-2.0.
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { ROOT, emit } from "./lib.mjs";

const check = process.argv.includes("--check");
const DIR = join(ROOT, "examples", "v0.1", "traces");

const TRACES = [
  { file: "core-lockstep.jsonl", title: "Core flow, lockstep",
    intro: "Discovery, session opening, the initial observation, one extended action across two advances with progress and completion, and closure, on the inline binding against a grid world." },
  { file: "core-streaming.jsonl", title: "Core flow, streaming",
    intro: "The same flow against a streaming manipulator: clock synchronization on the heartbeat, frames with capture and send time, a submission naming its basis, progress, completion, telemetry in both directions, and closure." },
  { file: "cancel.jsonl", title: "Cancellation during execution",
    intro: "An executing extended action is cancelled: the world enters cancelling, completes its safe abort, and reports cancelled with the progress reached." },
  { file: "disconnect.jsonl", title: "Disconnection, watchdog, resumption",
    intro: "The control connection drops mid-execution. The watchdog enters safe state and terminates the action while the agent is away; the agent reconnects, resumes, receives every missed notification in order, and regains control with a new submission." },
  { file: "retry.jsonl", title: "Lost acknowledgement, resumption, and resubmission",
    intro: "An admission result is lost with the connection. The agent reconnects before the world notices, resumes, receives the lost admission on replay, retries the submission idempotently, and has a conflicting reuse of the same action_id rejected; the queued action runs when the group frees." },
  { file: "estop.jsonl", title: "E-stop during a safe abort",
    intro: "An e-stop arrives while a cancelled action is still aborting and while another waits in the queue. Precedence ends the aborting action failed and the queued one cancelled; a submission during the e-stop is refused without creating an action, and succeeds unchanged after release." },
  { file: "approval.jsonl", title: "Approval granted and timed out",
    intro: "The agent's side of human-in-the-loop approval: one action is approved and executes; another receives no decision and is rejected at the approval timeout without executing." },
  { file: "close-during-motion.jsonl", title: "Close during motion",
    intro: "The agent closes while an action is executing. The action is aborted through cancelling, a submission while the session is closing is refused, and the close is answered only once the action has ended and the session is closed." },
  { file: "lockstep-replace.jsonl", title: "Replace in lockstep",
    intro: "A replacing submission against an executing lockstep action is admitted and staged; the running action is preempted at the start of the next advance, not at admission." },
  { file: "quiet-agent.jsonl", title: "Quiet agent on a live connection",
    intro: "The agent's decision loop stalls while its transport keeps answering pings. The watchdog, which counts only messages the agent originates, enters safe state on a healthy connection; a fresh intent resumes control." },
];

const esc = (s) => s.replace(/</g, "&lt;").replace(/\{/g, "&#123;").replace(/\}/g, "&#125;");
const arrow = (from) => (from === "agent" ? "agent → world" : "world → agent");

// JSON with two-space indent, arrays of primitives kept on one line.
function pretty(v, indent = "") {
  if (Array.isArray(v)) {
    if (v.every((x) => x === null || typeof x !== "object")) return JSON.stringify(v).replace(/,/g, ", ");
    return "[\n" + v.map((x) => indent + "  " + pretty(x, indent + "  ")).join(",\n") + "\n" + indent + "]";
  }
  if (v && typeof v === "object") {
    const entries = Object.entries(v);
    if (!entries.length) return "{}";
    return "{\n" + entries.map(([k, x]) => `${indent}  ${JSON.stringify(k)}: ${pretty(x, indent + "  ")}`).join(",\n") + "\n" + indent + "}";
  }
  return JSON.stringify(v);
}

let out = `---
title: "Wire traces"
description: "Complete, validated message sequences: discovery and session opening, the lockstep and streaming loops, cancellation, disconnection and recovery, retries, e-stop, approval, and the watchdog."
---

{/* GENERATED by scripts/gen-traces.mjs from examples/v0.1/traces/*.jsonl — do not edit by hand. */}

<Note>
Each trace is a JSON Lines file under [\`examples/v0.1/traces/\`](https://github.com/Hyperduality/agent-world-protocol/tree/main/examples/v0.1/traces). Every line is either a message, \`{ from, step, msg }\`, or a transport event that is not a message, \`{ marker }\`. A message marked *not delivered* was sent but lost with its connection. Every message validates against the sender form of the canonical schema for its method, and every response matches its request. The traces also hold to the protocol's meaning: every action follows the [transition table](/spec/loop/action-lifecycle) with a permitted reason and reaches one terminal state; resubmissions are idempotent or conflicts (AWP-ACT-001); \`status_seq\` is gapless across statuses, events, session-state notifications, and admission results, and after \`session.resume\` replay starts at \`last_status_seq\` + 1 and repeats exactly what was first reported (AWP-CTL-008); frame \`seq\` is checked per channel against its loss class (AWP-DAT-001, AWP-TRN-008); a closing session refuses new work and answers \`session.close\` only after every action has ended (AWP-SES-011); and where a trace names t0, safe-state entry falls between \`watchdog_ms\` and \`watchdog_ms\` + 100 ms after it with no agent-originated message in between (AWP-SAF-003, AWP-SAF-012). Tokens are illustrative.
</Note>

`;
let allOk = true;
for (const f of readdirSync(DIR).filter((f) => f.endsWith(".jsonl"))) {
  if (!TRACES.some((t) => t.file === f)) { console.error(`examples/v0.1/traces/${f} is not listed in scripts/gen-traces.mjs`); allOk = false; }
}
for (const t of TRACES) {
  const lines = readFileSync(join(DIR, t.file), "utf8").split("\n").filter((l) => l.trim());
  out += `## ${t.title}\n\n${t.intro} Source: [\`${t.file}\`](https://github.com/Hyperduality/agent-world-protocol/blob/main/examples/v0.1/traces/${t.file}).\n\n`;
  let n = 0;
  for (const line of lines) {
    const e = JSON.parse(line);
    if (e.marker) { out += `> **Transport.** ${esc(e.marker)}\n\n`; continue; }
    n++;
    out += `**${n}. ${esc(e.step)}** — ${arrow(e.from)}${e.delivered === false ? " *(not delivered)*" : ""}\n\n\`\`\`json\n${pretty(e.msg)}\n\`\`\`\n\n`;
  }
}
allOk = emit(join(ROOT, "spec", "wire-traces.mdx"), out, check) && allOk;
process.exit(allOk ? 0 : 1);
