#!/usr/bin/env node
// Generates generated/awp-v0.1.d.ts from the canonical schemas. `--check` fails on drift. Apache-2.0.
import { join, dirname } from "node:path";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { compile } from "json-schema-to-typescript";
import { ROOT, loadSchemas, emit } from "./lib.mjs";

const check = process.argv.includes("--check");
const schemas = loadSchemas();

/** Embedded JSON Schema documents (params_schema etc.) become plain objects in TypeScript; the
 *  meta-schema $ref cannot be resolved offline and would not produce a useful type anyway. */
function stripMetaRefs(node) {
  if (Array.isArray(node)) return node.map(stripMetaRefs);
  if (node && typeof node === "object") {
    if (typeof node.$ref === "string" && node.$ref.includes("json-schema.org")) {
      return { type: "object", tsType: "Record<string, unknown>", description: node.description };
    }
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, stripMetaRefs(v)]));
  }
  return node;
}

// The ref parser resolves sibling files from disk, so stripped copies of every schema go to a temp dir.
const work = mkdtempSync(join(tmpdir(), "awp-schemas-"));
const pascal = (s) => s.split(/[-/]/).map((w) => w[0].toUpperCase() + w.slice(1)).join("");
const stripped = schemas.map(({ name, file, schema }) => ({
  name,
  file,
  // Type names come from `title`; use the file name so exports read WorldManifest, SessionReady, ...
  schema: { ...stripMetaRefs(schema), title: pascal(name) },
}));
for (const { file, schema } of stripped) {
  mkdirSync(dirname(join(work, file)), { recursive: true });
  writeFileSync(join(work, file), JSON.stringify(schema));
}

let out = `// GENERATED by scripts/gen-types.mjs from schemas/v0.1/*.schema.json — do not edit by hand.\n// Apache-2.0. Protocol v0.1 (draft).\n\n`;
const seen = new Set();
for (const { name, schema } of stripped) {
  const ts = await compile(schema, name, {
    cwd: dirname(join(work, name)),
    bannerComment: "",
    declareExternallyReferenced: true,
    additionalProperties: false,
    style: { singleQuote: false, semi: true },
    $refOptions: { resolve: { http: false } },
  });
  // Drop duplicate declarations produced when several schemas pull in the same $defs.
  for (const block of ts.split(/\n(?=export |\/\*\*)/)) {
    const m = block.match(/export (?:interface|type) (\w+)/);
    if (m) {
      if (seen.has(m[1])) continue;
      seen.add(m[1]);
    }
    out += block.trim() + "\n\n";
  }
}

rmSync(work, { recursive: true, force: true });
process.exit(emit(join(ROOT, "generated", "awp-v0.1.d.ts"), out, check) ? 0 : 1);
